title: GitHub Jekyll Page
author: William A Ellerbe
email: waellerbe@gmail.com
minima:
description: > # this means to ignore newlines until "baseurl:"
  My GitHub page is coming along. With this step we need to edit
  a few lines within the _config.yml file. I understand that
  information for this project will appear in my document head as
  meta data (for Google search results) and in my feed.xml
  site description.

# social links
github_username:  github.com/waellerbe/ # I do not use Twitter

show_excerpts: true # set to false to remove excerpts on the homepage
